import Header from "@/components/header/Header";

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../app/globals.css";

const roboto = Roboto({
    weight: "400",
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body className={roboto.className}>
                <Header />
                {children}
            </body>
        </html>
    );
}
